### PR TITLE
Upgrading to Capsule v0.0.3 and using ISO-8601 for ts log field

### LINKED ISSUE #35: Changing the logs ts field from timestamp to date
Changing the logs ts field from timestamp to date as we done in https://github.com/clastix/capsule/issues/139

### PR DESCRIPTION
**Pull request by prometherion**
Closes #35.

@bsctl would you mind testing it before merging?

### CODE REVIEW

**Review by bsctl — COMMENTED** [review]
@prometherion it looks current PR branch lacks of #34 
`https://github.com/clastix/capsule-ns-filter/blob/8b63916888df8b36d93f3da05bbcd5c7ec7b65ea/internal/webserver/webserver.go#L153`

Pls check.

**Comment by prometherion** [comment]
It doesn't look to me.
https://github.com/clastix/capsule-ns-filter/blob/8b63916888df8b36d93f3da05bbcd5c7ec7b65ea/internal/webserver/webserver.go#L153

Anyway checking on the laptop, I'll be back to you.

**Comment by bsctl** [comment]
It should be Set instead of Add https://github.com/clastix/capsule-ns-filter/pull/34#discussion_r517607066

**Comment by prometherion** [comment]
Rebased and it looks good: since we're squashing that chang would have replicated. 🤦🏻

**Comment by bsctl** [comment]
@prometherion LGTM +1 Going to squash and merge.

**Pull request merged**
